### ISSUE TITLE
[Bug] The IVA portrait toggle button doesn't appear in the game Appbar

### ISSUE THREAD

**Issue by hikerchick29** [KSP2Community/KerbalLifeHacks#7]
The issue is as described.  The new IVA portrait toggle function isn't present.

**Comment by jan-bures** [comment]
Could you send a screenshot of the flight view please?

**Comment by hikerchick29** [comment]
![Uploading Kerbal Space Program 2 1_23_2024 12_17_00 AM.png…]()

**Comment by hikerchick29** [comment]
![Kerbal Space Program 2 1_23_2024 12_17_00 AM](https://github.com/KSP2Community/KerbalLifeHacks/assets/50774225/eca36a82-9ce9-4d60-bedf-ee46ad9d5831)

**Comment by jan-bures** [comment]
Yeah that's definitely wrong, could you send the logs please?

**Comment by jan-bures** [comment]
Alright, I've identified the issue, it should be fixed in #9.
